# Generated by Django 6.0.2 on 2026-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.CharField(choices=[('None', 'No Badge'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='None', max_length=20),
        ),
    ]
