# Generated by Django 6.0.2 on 2026-03-05 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_title_event_name_remove_event_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'student')},
        ),
    ]
