# Generated by Django 6.0.2 on 2026-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_profile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='old@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
