# Generated by Django 6.0.2 on 2026-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
